title: Benjamin Yung # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Business Analyst 
  <br><br>
  M.S. in Commerce 
  B.A. in Economics
  <br><br>
  <a href="https://www.linkedin.com/in/-ben-yung/">View Ben's LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
